"""
Cell Ranger 工具
支持生成脚本和执行 Cell Ranger 分析
"""
import os
import sys
import subprocess
import shutil
import logging
from typing import Dict, Any, List, Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class CellRangerTool:
    """
    Cell Ranger 工具
    
    支持：
    1. 生成脚本
    2. 执行 Cell Ranger count
    3. 检测 FASTQ 文件结构
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """
        初始化 Cell Ranger 工具
        
        Args:
            config: 配置字典，包含 cellranger 路径、参考基因组等
        """
        self.config = config or {}
        # 支持完整路径（如 /home/ubuntu/cellranger-10.0.0）或目录路径
        cellranger_path = self.config.get("path", "/opt/cellranger")
        if os.path.isfile(cellranger_path):
            # 如果是文件路径，使用目录
            self.cellranger_path = os.path.dirname(cellranger_path)
        elif os.path.isdir(cellranger_path):
            # 如果是目录，检查是否有 bin/cellranger
            if os.path.exists(os.path.join(cellranger_path, "bin", "cellranger")):
                self.cellranger_path = cellranger_path
            else:
                # 可能是旧版本，直接使用目录
                self.cellranger_path = cellranger_path
        else:
            # 默认路径
            self.cellranger_path = cellranger_path
        
        self.cellranger_bin = os.path.join(self.cellranger_path, "bin", "cellranger")
        if not os.path.exists(self.cellranger_bin):
            # 尝试旧版本路径
            self.cellranger_bin = os.path.join(self.cellranger_path, "cellranger")
        
        self.reference = self.config.get("reference", "/data/refdata-cellranger-GRCh38-3.0.0")
    
    def generate_count_script(
        self,
        fastq_dir: str,
        sample_id: str,
        output_dir: str,
        reference: Optional[str] = None,
        localcores: int = 8,
        localmem: int = 64
    ) -> str:
        """
        生成 cellranger count 脚本
        
        Args:
            fastq_dir: FASTQ 文件目录路径
            sample_id: 样本 ID
            output_dir: 输出目录路径
            reference: 参考基因组路径（可选）
            localcores: 本地核心数
            localmem: 本地内存（GB）
        
        Returns:
            Bash 脚本内容
        """
        reference = reference or self.reference
        
        script = f"""#!/bin/bash
# Cell Ranger Count Script
# Generated by GIBH-Agent

set -e

# 配置
CELLRANGER_PATH="{self.cellranger_path}"
REFERENCE="{reference}"
FASTQ_DIR="{fastq_dir}"
SAMPLE_ID="{sample_id}"
OUTPUT_DIR="{output_dir}"

# 环境变量
export PATH=$CELLRANGER_PATH:$PATH

# 执行 cellranger count
$CELLRANGER_PATH/cellranger count \\
    --id=$SAMPLE_ID \\
    --transcriptome=$REFERENCE \\
    --fastqs=$FASTQ_DIR \\
    --localcores={localcores} \\
    --localmem={localmem} \\
    --expect-cells=3000

# 移动结果到输出目录
if [ -d "$SAMPLE_ID/outs" ]; then
    mkdir -p $OUTPUT_DIR
    mv $SAMPLE_ID/outs/* $OUTPUT_DIR/
    echo "Cell Ranger count completed. Results in: $OUTPUT_DIR"
else
    echo "Error: Cell Ranger count failed"
    exit 1
fi
"""
        return script
    
    def generate_aggr_script(
        self,
        sample_dirs: List[str],
        sample_ids: List[str],
        output_dir: str,
        aggregation_csv: Optional[str] = None
    ) -> str:
        """
        生成 cellranger aggr 脚本（合并多个样本）
        
        Args:
            sample_dirs: 样本目录列表
            sample_ids: 样本 ID 列表
            output_dir: 输出目录
            aggregation_csv: 聚合 CSV 文件路径（可选）
        
        Returns:
            Bash 脚本内容
        """
        if aggregation_csv:
            csv_option = f"--csv={aggregation_csv}"
        else:
            # 生成临时 CSV
            csv_lines = ["library_id,molecule_h5"]
            for sid, sdir in zip(sample_ids, sample_dirs):
                csv_lines.append(f"{sid},{sdir}/molecule_info.h5")
            csv_content = "\\n".join(csv_lines)
            csv_option = f"--csv=<(echo -e \"{csv_content}\")"
        
        script = f"""#!/bin/bash
# Cell Ranger Aggr Script
# Generated by GIBH-Agent

set -e

CELLRANGER_PATH="{self.cellranger_path}"
OUTPUT_DIR="{output_dir}"

export PATH=$CELLRANGER_PATH:$PATH

# 执行 cellranger aggr
$CELLRANGER_PATH/cellranger aggr \\
    --id=aggregated \\
    {csv_option}

# 移动结果
if [ -d "aggregated/outs" ]; then
    mkdir -p $OUTPUT_DIR
    mv aggregated/outs/* $OUTPUT_DIR/
    echo "Cell Ranger aggr completed. Results in: $OUTPUT_DIR"
else
    echo "Error: Cell Ranger aggr failed"
    exit 1
fi
"""
        return script
    
    def detect_fastq_structure(self, fastq_dir: str) -> Dict[str, Any]:
        """
        检测 FASTQ 文件结构
        
        只检查文件路径，不读取文件内容
        
        Args:
            fastq_dir: FASTQ 目录路径
        
        Returns:
            结构信息字典
        """
        fastq_path = Path(fastq_dir)
        
        if not fastq_path.exists():
            return {"error": "Directory does not exist"}
        
        # 查找 FASTQ 文件
        fastq_files = list(fastq_path.glob("*.fastq*"))
        
        # 检测 10x 结构
        has_r1 = any("R1" in f.name or "_1" in f.name for f in fastq_files)
        has_r2 = any("R2" in f.name or "_2" in f.name for f in fastq_files)
        has_i1 = any("I1" in f.name or "_index" in f.name for f in fastq_files)
        
        return {
            "type": "10x" if (has_r1 and has_r2) else "standard",
            "num_files": len(fastq_files),
            "has_index": has_i1,
            "files": [str(f) for f in fastq_files[:10]]  # 只返回前10个文件路径
        }
    
    def run_count(
        self,
        fastq_dir: str,
        sample_id: str,
        output_dir: str,
        reference: Optional[str] = None,
        sample: Optional[str] = None,
        localcores: int = 8,
        localmem: int = 32,
        create_bam: bool = False,
        expect_cells: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        执行 cellranger count
        
        Args:
            fastq_dir: FASTQ 文件目录路径
            sample_id: 样本 ID（也是输出目录名）
            output_dir: 最终输出目录路径
            reference: 参考基因组路径（可选）
            sample: 样本名称（从 FASTQ 文件名提取，可选）
            localcores: 本地核心数
            localmem: 本地内存（GB）
            create_bam: 是否创建 BAM 文件（Cell Ranger 10.0.0+ 必需参数）
            expect_cells: 预期细胞数（可选）
        
        Returns:
            执行结果字典，包含：
            - status: "success" 或 "error"
            - output_dir: 输出目录路径
            - matrix_dir: 矩阵目录路径（用于后续转换）
            - error: 错误信息（如果有）
        """
        reference = reference or self.reference
        
        # 将所有路径转换为绝对路径，避免工作目录问题
        fastq_dir = os.path.abspath(fastq_dir)
        reference = os.path.abspath(reference)
        output_dir = os.path.abspath(output_dir)
        
        # 检查 Cell Ranger 是否存在
        if not os.path.exists(self.cellranger_bin):
            return {
                "status": "error",
                "error": f"Cell Ranger not found at: {self.cellranger_bin}",
                "output_dir": None,
                "matrix_dir": None
            }
        
        # 检查 FASTQ 目录
        if not os.path.exists(fastq_dir):
            return {
                "status": "error",
                "error": f"FASTQ directory does not exist: {fastq_dir}",
                "output_dir": None,
                "matrix_dir": None
            }
        
        # 检查参考基因组
        if not os.path.exists(reference):
            return {
                "status": "error",
                "error": f"Reference genome does not exist: {reference}",
                "output_dir": None,
                "matrix_dir": None
            }
        
        # 确定工作目录：Cell Ranger 会在当前目录创建 {sample_id} 文件夹
        # 我们需要在输出目录的父目录运行，这样 {sample_id} 会创建在正确的位置
        work_dir = os.path.dirname(output_dir) if os.path.dirname(output_dir) else os.getcwd()
        work_dir = os.path.abspath(work_dir)  # 确保是绝对路径
        
        # 构建命令（使用绝对路径）
        cmd = [
            self.cellranger_bin,
            "count",
            "--id", sample_id,
            "--create-bam", "true" if create_bam else "false",
            "--transcriptome", reference,
            "--fastqs", fastq_dir,
            "--localcores", str(localcores),
            "--localmem", str(localmem)
        ]
        
        # 添加可选参数
        if sample:
            cmd.extend(["--sample", sample])
        if expect_cells:
            cmd.extend(["--expect-cells", str(expect_cells)])
        
        # 设置环境变量
        env = os.environ.copy()
        env["PATH"] = f"{self.cellranger_path}/bin:{env.get('PATH', '')}"
        
        try:
            # 执行命令
            logger.info("🚀 Running Cell Ranger count...")
            logger.info(f"   Command: {' '.join(cmd)}")
            logger.info(f"   Working directory: {work_dir}")
            print(f"🚀 Running Cell Ranger count...")
            print(f"   Command: {' '.join(cmd)}")
            print(f"   Working directory: {work_dir}")
            sys.stdout.flush()
            
            # 实时输出日志：使用 Popen 而不是 run，以便实时捕获输出
            process = subprocess.Popen(
                cmd,
                cwd=work_dir,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,  # 合并 stderr 到 stdout
                text=True,
                bufsize=1,  # 行缓冲
                universal_newlines=True
            )
            
            # 实时读取并输出日志
            stdout_lines = []
            
            # 从进程实时读取输出
            while True:
                output = process.stdout.readline()
                if output == '' and process.poll() is not None:
                    break
                if output:
                    line = output.strip()
                    if line:  # 忽略空行
                        stdout_lines.append(line)
                        # 实时输出到终端和日志系统
                        log_msg = f"[Cell Ranger] {line}"
                        logger.info(log_msg)
                        print(f"   {log_msg}")
                        sys.stdout.flush()  # 确保立即输出
            
            # 等待进程完成
            returncode = process.poll()
            
            # 构建完整的输出
            stdout = '\n'.join(stdout_lines)
            stderr = ''  # 已合并到 stdout
            
            # 创建类似 subprocess.run 的结果对象
            class Result:
                def __init__(self, returncode, stdout, stderr):
                    self.returncode = returncode
                    self.stdout = stdout
                    self.stderr = stderr
            
            result = Result(returncode, stdout, stderr)
            
            # Cell Ranger 会在 work_dir 下创建 {sample_id} 目录
            output_path = os.path.join(work_dir, sample_id, "outs")
            matrix_dir = os.path.join(output_path, "filtered_feature_bc_matrix")
            
            if result.returncode == 0 and os.path.exists(matrix_dir):
                # Cell Ranger 在 work_dir 下创建了 {sample_id} 目录
                # 如果指定的 output_dir 与创建的位置不同，需要移动结果
                cellranger_output = os.path.join(work_dir, sample_id)
                if os.path.abspath(output_dir) != os.path.abspath(cellranger_output):
                    # 确保目标目录的父目录存在
                    os.makedirs(os.path.dirname(output_dir), exist_ok=True)
                    # 如果目标目录已存在，先删除
                    if os.path.exists(output_dir):
                        shutil.rmtree(output_dir)
                    # 移动整个 {sample_id} 目录到 output_dir
                    shutil.move(cellranger_output, output_dir)
                    matrix_dir = os.path.join(output_dir, "outs", "filtered_feature_bc_matrix")
                else:
                    # 如果位置相同，直接使用
                    matrix_dir = os.path.join(output_dir, "outs", "filtered_feature_bc_matrix")
                
                return {
                    "status": "success",
                    "output_dir": output_dir,
                    "matrix_dir": matrix_dir,
                    "stdout": result.stdout,
                    "stderr": result.stderr
                }
            else:
                # 输出错误信息以便调试
                error_msg = f"Cell Ranger count failed with return code {result.returncode}"
                if result.stderr:
                    error_msg += f"\nSTDERR: {result.stderr[:500]}"  # 只显示前500字符
                if result.stdout:
                    error_msg += f"\nSTDOUT: {result.stdout[:500]}"
                
                return {
                    "status": "error",
                    "error": error_msg,
                    "stdout": result.stdout,
                    "stderr": result.stderr,
                    "output_dir": None,
                    "matrix_dir": None
                }
        except Exception as e:
            return {
                "status": "error",
                "error": f"Exception while running Cell Ranger: {str(e)}",
                "output_dir": None,
                "matrix_dir": None
        }

